apiVersion: v1
kind: Service
metadata:
  name: cerverjaria-acme-service
  namespace: cervejaria
spec:
  selector:
    app: cervejaria-acme
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30010
  type: NodePort
  